### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 12th 2024 to @chribaue and @fedorov with @lassoan in cc:

```
Subject: Help to merge https://github.com/QIICR/Slicer-PETDICOMExtension/pull/23

Hi Christian and Andrey,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/QIICR/Slicer-PETDICOMExtension/pull/23

Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Comment by fedorov** [comment]
Sorry for missing the original notification!

**Comment by jcfr** [comment]
@fedorov  Thanks for taking the time to follow-up :pray: :rocket:

**Pull request merged**
